### ISSUE TITLE
Error: SvtAv1EncApp program not found

### ISSUE THREAD

**Issue by marcin-przywoski** [alexheretic/ab-av1#102]
When trying to run the vmaf comparison AND encoding I'm getting the following error. I have ffmpeg with all the required components in $Path since I can encode in AV1 from cmd using ffmpeg commands. Is it possible for anyone to guide me here?

I'm using Windows 11, latest build available

**Comment by alexheretic** [comment]
The latest release v0.6.1 [requires SvtAv1EncApp](https://github.com/alexheretic/ab-av1/tree/4823b33a6d33d9b4470a56dee1ffe1152d77e140#requirements). However, that requirement has been recently removed in the main branch code since new releases will use ffmpeg-libsvtav1 instead.

You can try [installing the latest git](https://github.com/alexheretic/ab-av1#using-cargo) or waiting for the next release. Otherwise you could make SvtAv1EncApp available on your PATH and continue using v0.6.1.

**Comment by marcin-przywoski** [comment]
Thanks, I've downloaded SvtAv1EncApp.exe and put it in the $PATH and that has fixed the issues. There is another issue with vmaf not working when comparing files throwing errors about ffmpeg which is strange cause crf-search works fine
