### ISSUE TITLE
Try to get the highest achievable VMAF score, while batch processing a folder

### ISSUE THREAD

**Issue by BankaiNoJutsu** [alexheretic/ab-av1#105]
Hey,

I was wondering how the auto encode works, does it specifically try to hit a vmaf of 95 by default? Is there any option to hit the highest achievable, i.e. if a higher vmaf than 95 can he hit, then favour it?

Also, would it be possible to implement a batch/multi file processing on a folder basis, using walkdir with metadata recognition of video files? I'll look into the code to see if it doesn't add to much complexity.

I thought these two features would be a great addition, at least for my use cases.

What are your thoughts?

**Comment by alexheretic** [comment]
_auto-encode_/_crf-search_ are indeed trying to find the highest crf value to satisfy the --min-vmaf and --max-encoded-percent (default 95 & 80 respectively).

You can configure these.

There was some discussion about handling multiple min-vmaf values in #49. The current solution is to try a high vmaf then if that fails try lower vmafs, caching makes this fairly efficient.

For recursive/multi-input there is no current support. But it's possible to do with a simple script, since (in general) ab-av1 encoding won't benefit from running concurrently.

**Comment by BankaiNoJutsu** [comment]
Thanks for the reply!

Okay, so I just target with --min-vmaf.

I actually made a small rust app called ab-av1-walkdir that does that: https://github.com/BankaiNoJutsu/ab-av1-walkdir
