### ISSUE TITLE
SSIMULACRA2

### ISSUE THREAD

**Issue by devedse** [alexheretic/ab-av1#167]
Hello, I was windering if you'd be interested in adding SSIMULACRA2 as an alternative to VMAF?

Kind regards Devedse

**Comment by devedse** [comment]
Hmm that's too bad. I guess you could "deliver" everything as a docker solution which can be ran from the command line which would then call the compiled SSIMULCRA2 binary but I'm not sure if that's the most ideal solution either.

**Comment by veikk0** [comment]
Note: I'm not the developer, just a user providing some background and opinions.

Previously, ab-av1 used SvtAv1EncApp directly, so there was a lot more piping involved, there were some colorspace conversion issues with that I think (at least from my experience as a user), and it was just a bit messy. Going FFmpeg-only made things much better, at least from an installation and usage point of view. And though I have no experience with working on the ab-av1 code, I have used encoders by piping raw video, and it's always an added layer of complexity (and a point of failure) over just being able to use FFmpeg.

The SSIMULACRA 2 Rust implementation is a library, so that would be a single dependency and can be easily installed with Cargo. But currently I think ab-av1 uses FFmpeg by calling the binary and parsing text, so I don't know if there's a desire to calculate a metric using a library and what exactly that would involve.

**Comment by alexheretic** [comment]
Yes ideally it would be done via ffmpeg. However, perhaps it would be possible to pipe ffmpeg into a `ab-av1 ssimulacra2` process using the rust crate. This needs investigation.

We already have an issue for this #104, so I'll close here and we can continue the discussion there.
