### ISSUE TITLE
Sample clips rarely 20 seconds long

### ISSUE THREAD

**Issue by veikk0** [alexheretic/ab-av1#36]
In my use, the clips copied from the source with FFmpeg for VMAF sampling are rarely 20 seconds long. The cause seems to be using the `-ss` command as an output option rather than as an input option (before the `-i` option). My theory is that for reasons known only to itself, FFmpeg is using the GOP as its smallest unit of measurement when cutting and is thus leaving the clip one GOP short (instead of making it too long or just copying the number of frames necessary).

For example, with my input material (60 fps content encoded with x264 and a keyint of 250, so a key frame at least every 4.16 seconds), the following command will produce clips that are almost exactly 4.16 seconds too short:

>ffmpeg -i input.mp4 -ss 30 -c:v copy -an -t 20 output.mp4

Media players and tools like mediainfo might misreport the length of the clip as 20 seconds, but looking at the length of the encoded AV1 files or counting the number of frames with ffprobe should reveal the issue:

>ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 -threads auto output.mp4

As for fixes, moving the `-ss` option to before `-i` works for me and seems to be the most simple solution. However, in my tests, this consistently copies two more frames than necessary (1202 frames instead of 1200). The way to get exactly the right number of frames would be to figure out the number of frames in 20 seconds based on the content fps and using `-frames:v` to copy that number.

Normally I'd say go with the first option since it's accurate enough, but I've also discovered a bug (maybe [this one](https://trac.ffmpeg.org/ticket/8515)?) in FFmpeg's VC-1 decoder. This manifests as garbled frames until the next keyframe when copying VC-1 video (sourced from Blu-ray discs) when using the -ss option before the input. So for compatibility with older Blu-ray material, using -ss after the input and copying a number of frames would be better.

**Comment by alexheretic** [comment]
Interesting, thanks for raising.

I guess the other factor is that having exactly 20s samples isn't
particularly important in itself, if they still act as a decent way to
approximate vmaf scores. It's also preferable to have fast sample creation.

So I wonder what the best action in this case would be? E.g. perhaps we
could detect this case by checking the GOP and request 20s+GOP samples for
particular codecs? Perhaps if the keyint is less than 10s, the samples
10-20s, it doesn't make a huge difference to the sample vmaf scores?

Can we find some examples videos that would produce very poor samples, e.g.
only a few seconds long?

**Comment by veikk0** [comment]
I don't think that a 10s sample length would negatively affect accuracy as long as you used enough samples. My gut feeling is that it would actually be more accurate for the same amount of CPU cycles, especially for content with a lot of variety.

I've actually been hoping that the clip length was user-configurable, so I could halve the length and double the number of samples but still use roughly the same amount of compute overall. 

I'm leaning towards the `-frames:v` approach, with the number of frames being calculated from fps * seconds. Using GOP based would have some inherent accuracy issues, and the GOP length of  the source material isn't under our control. Who knows what kind of strange videos users will use as input, like something with 60+ second GOPs encoded with a DIY security camera setup?

**Comment by alexheretic** [comment]
I think I agree overall, it's better if the samples act in the most predictable way as long (as the performance is ok).

I'd be interested in testing some weird keyint encodings to see how ffmpeg acts with the current logic.

**Comment by alexheretic** [comment]
Hey sorry for the delay, I've taken some time to try various approaches on some videos.

## Sample generation methods
## -ss output (current approach)
    ffmpeg -y -i $VID -ss $SAMPLE_START -t 20 -c:v copy -an $SAMPLE

## -ss input
    ffmpeg -y -ss $SAMPLE_START -i $VID -t 20 -c:v copy -an $SAMPLE

## -ss output -frames:v
    ffmpeg -y -i $VID -ss $SAMPLE_START -frames:v $FRAMES -c:v copy -an $SAMPLE

## -ss input -frames:v
    ffmpeg -y -ss $SAMPLE_START -i $VID -frames:v $FRAMES -c:v copy -an $SAMPLE

## vid-a.mp4
length 29.01, h264, 25fps
<details>

### -ss output
485 frames = 19.4s (generated in 54ms)
447 frames = 17.9s (generated in 87ms)

### -ss input
502 frames = 20.9s (generated in 26ms)
502 frames = 20.9s (generated in 28ms)

### -ss output -frames:v
500 frames = 20s (generated in 55ms)
500 frames = 20s (generated in 83ms)

### -ss input -frames:v
500 frames = 20s (generated in 26ms)
500 frames = 20s (generated in 25ms)

</details>

## vid-b.mkv
length 11:12, av1, 23.98fps
<details>

### -ss output
350 frames = 14.6s (generated in 38ms)
443 frames = 18.5s (generated in 60ms)

### -ss input
590 frames = 24.6s (generated in 22ms)
584 frames = 24.4s (generated in 24ms)

### -ss output -frames:v
480 frames = 20s (generated in 41ms)
480 frames = 20s (generated in 57ms)

### -ss input -frames:v
480 frames = 20s (generated in 20ms)
480 frames = 20s (generated in 21ms)

</details>

## vid-c.mkv
length 1:40:36, h264, 23.98fps
<details>

### -ss output
415 frame = 17.3s (generated in 225ms)
422 frame = 17.6s (generated in 429ms)

### -ss input
553 frames = 23.1s (generated in 37ms)
494 frames = 20.6s (generated in 35ms)

### -ss output -frames:v
480 frames = 20s  (generated in 227ms)
480 frames = 20s  (generated in 435ms)

### -ss input -frames:v
480 frames = 20s  (generated in 35ms)
480 frames = 20s  (generated in 34ms)

</details>

## vid-c.mkv re-encoded with 20min key interval (1 sample)
<details>

### -ss output
0 frames

### -ss input
10455 frames = 436s

### -ss output -frames:v
480 frames = 20s (generated in 579ms)
* ends up as a ~13m video with final 20s working
* re-encodes as a ~13m video with a still image until the last 20s
* re-encoding is slow & vmaf is slow due to length

### -ss input -frames:v
480 frames = 20s (generated in 22ms)
* But the wrong 20s (taken from the key frame)
* Re-encodes fine

</details>

## Remarks
From these results the current approach is probably the _worst_ of the four. It's slow, inaccurate and doesn't work at all for videos with extreme key intervals.

The best option seems to be **-ss input -frames:v** it is fast and frame accurate. It does seem to start from the nearest key frame, meaning it isn't creating the "correct" sample in the extreme key interval case. However, it still behaves the best even then as none of the methods handle that properly.

So I think I'll make method 4 the new approach.
