### ISSUE TITLE
Default output to .mkv/.mp4 container

### ISSUE THREAD

**Issue by alexheretic** [alexheretic/ab-av1#72]
Currently we use the same output container as input. This has issues when the input container doesn't support av1, or the overridden encoder codec. However, outputting mkv -> mkv is desirable.

New behaviour:
* If `-o` is specified use that (and use that for `-e` samples too).
* If input is .mkv default to .mkv output.
* Otherwise use .mp4.

This should work better in more cases while still be controllable if a different container is desired.

**Comment by iPaulis** [comment]
Just out of curiosity, why use mp4 as default fallback container and not mkv? both containers support most codecs, so maybe there is no real difference, I was just wondering why to choose mp4 over mkv.

**Comment by alexheretic** [comment]
mp4 is better for streaming and sometimes has better support (though if mkv wasn't supported I doubt av1 would be either).

Honestly there I don't have a strong preference, which is why I started just using the input container/extension. I could be convinced to default to mkv instead (maintaining mp4 -> mp4 ofc). Should we?

**Comment by iPaulis** [comment]
Honetly, I don't have a good answer for that question, that is why I was asking.

As you said, mp4 supports streaming better and is usually more compatible to be reproduced in most devices by default.
However, as containers, it was my understanding that mkv can contain anything, it supports absolutely any codec, while mp4 supports most, but not all of them. There are some video and audio codecs, such as FLAC, not supported by mp4, as well as, multiple subtitle tracks and some subtitle formats like SSA/ASS, also not supported. That is why most source video files from TV/movies nowadays are usually in mkv.

Besides, mkv is an open source container while mp4 is not, it is the most compatible container, it has active development and community support, and there are many free and open-source tools to work with mkv and manipulate whatever it contains easily.

I think I would go with mkv as default just in case, because it is less likely to fail and should be the most suitable in most of the scenarios and variety of source files. If someone needs something else, they could specify the output for their particular use case.

But as I said, there may be something I'm missing here, so I'm not completely sure.

**Comment by alexheretic** [comment]
Yeah I think I agree overall. The only downside of .mkv is it's easier to make mp4 stream friendly, it's built into ffmpeg and ab-av1 already adds `-movflags +faststart` for mp4s. 

It looks like a similar thing can be done for mkv too, just not via ffmpeg. So I'll leave that out of scope for now.

**Comment by alexheretic** [comment]
> It looks like a similar thing can be done for mkv too, just not via ffmpeg. So I'll leave that out of scope for now.

Hopefully fairly easily solved by #76
