### ISSUE TITLE
VMAF calculation is single-threaded & other stuff

### ISSUE THREAD

**Issue by veikk0** [alexheretic/ab-av1#9]
Due to the limitations of FFmpeg's integration of libvmaf, the number of threads you want VMAF to use needs to be specified manually. You'd do this like so: `libvmaf=n_threads=16`. If this isn't done, VMAF calculation defaults to a single thread.

Another useful parameter is `n_subsample=X`, which basically allows VMAF to be calculated only for every X frames. The amount of subsampling used while still maintaining good accuracy would depend somewhat on the sample length (for example, a subsampling of 6 for a one second 24fps sample would only calculate the VMAF for 4 frames, which could be too inaccurate). But even a subsampling of 2 or 3 would probably be accurate enough. Being user-specifiable would be best ofc.

These two options would speed up VMAF calculation a lot. I'm currently testing ab-av1 auto-encode with an old dual-core laptop and for a 1m15s 1920x1200 video and preset 12, and the ETA is 2 hours.

I think until relatively recently there were also other issues (like [this](https://trac.ffmpeg.org/ticket/9094), which required the model path to be specified manually), but there was an update to FFmpeg's libvmaf filter (December I think) to properly support libvmaf 2.0 and many of the issues are resolved. However, users on older versions might run into problems. It would probably be a good idea to recommend/require FFmpeg 5.0 as the minimum, since it's the first release that actually functions somewhat as you'd expect with libvmaf.

**Comment by alexheretic** [comment]
Hey, I'm build/testing on arch. Currently ffmpeg 4.4.1, vmaf 1.5.3. ffmpeg vmaf is absolutely using all 16 threads on my system. What OS and versions are you running? If you run manually and specify `n_threads=0` does it use all your threads? (That is [the documented default](https://ffmpeg.org/ffmpeg-filters.html#libvmaf), at least now).

I previously tested n_subsample across the whole video and found it does speed it up, but not be a huge amount. Doing full vmaf on small samples seems to be a much faster way to get an approximate VMAF. We could do both, it may be worth experimenting with though since the samples are already approx it could skew the accuracy too much.

Yes I agree it's a good idea to document minimum versions. Perhaps:
* ffmpeg v4.4.1
* vmaf v1.53
* svt-av1 v0.9

**Comment by veikk0** [comment]
For me, `n_threads=0` results in only one thread being used. I'm using a self-built git version of FFmpeg from four days ago, and the libvmaf version should be v2.3.0. Though I do have another VMAF installed system-wide and it's possible it's being picked up for the build instead. Neither version is pre-2.0 though.

I'm on Linux Mint 20.2 and building FFmpeg via a script cobbled together from [this page](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu) with some changes.

Those options would be good to have. They would help with the experimentation too, along with being able to adjust sampling, like the count and length of samples.

**Comment by alexheretic** [comment]
I've raised https://github.com/alexheretic/ab-av1/pull/11 to add `--vmaf-options` argument. Let me know if that looks good.

The `n_threads=0` multi-threading/not multi-threading issue I don't fully understand. For me this uses all cores. We could default this to the number of system cores instead of relying on libvmaf defaults. However, if its your perhaps older system vmaf that isn't using all cores and modern versions do maybe it's not needed?

It doesn't seem bad to default this to all cores, if no --vmaf-options are specified, as it's how I expect it to behave anyway.

**Comment by veikk0** [comment]
I'm also not sure why libvmaf is acting up. And it just got weirder.

I downloaded [John van Sickle's](https://johnvansickle.com/ffmpeg/) latest git build (which is from a month ago) to see if it behaves differently from mine and it acts like the updates to the libvmaf filters didn't happen at all. Ie. the model file needs to be specified manually. This also happens with his 5.0 build. The threading issue is also still there in both. And his build info says both builds use libvmaf 2.3.0, so it's not exactly old.

`--vmaf-options` is working without issues for me.

**Comment by alexheretic** [comment]
I've made some more changes to vmaf. We'll explicitly set `n_threads` to be the logical core count now, which should address the inconsistency of `n_threads=0` behaviour. I also reworked the vmaf options arg to be `--vmaf n_subsample=4` style.

**Comment by alexheretic** [comment]
I'll close this issue now as I think I addressed most of the stuff here. Specifying the model file by default is a bit trickier maybe across vmaf versions, so I may look into it later. Please raise more issues if I've missed stuff.
